collections:
  singles:
    output: true

defaults:
  - scope:
      path: ""
      type: "singles"
    values:
      layout: "single"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap


baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.almadetuz.com" # the base hostname & protocol for your site, e.g. http://example.com
logo: /assets/images/icon.png

exclude:
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - Procfile
  - convert_img.sh
  - resize_img.sh
  - config.ru
  - Rakefile

# SEO and OG global variables
title: Alma de Tüz
lang: es_ES
email: amanda@almadetuz.com
description: >-
  Arquitecturas sonoras para sanar
twitter:
  username: almadetuz
  card: summary
seo_image: /assets/images/alma_de_tuz_seo.jpg
seo_image_width: 1280
seo_image_height: 720
